"use client";

import { useSearchParams, useRouter } from "next/navigation";
import { useState, useEffect, FormEvent } from "react";
import type { Paper } from "@/types/paper";

// TODO: OpenAI integration — landscape, emergingAreas, researchGaps, and projects
// will be generated by GPT-4 using the query + PubMed paper abstracts as context.

// TODO: PubMed pipeline is live (ESearch → ESummary + EFetch in parallel).
// Future: supplement with GEO, SRA, ArrayExpress, Europe PMC, and TCGA datasets.

interface AnalysisResponse {
  landscape: string[];
  emergingAreas: string[];
  researchGaps: string[];
  projects: string[];
  datasets: string[];
  papers: Paper[];
}

export default function ResultsContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const q = searchParams.get("q") ?? "";

  const [query, setQuery] = useState(q);
  const [data, setData] = useState<AnalysisResponse | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!q.trim()) return;

    setIsLoading(true);
    setError(null);
    setData(null);

    fetch("/api/analyze", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ query: q }),
    })
      .then((res) => {
        if (!res.ok) throw new Error(`Server error: ${res.status}`);
        return res.json() as Promise<AnalysisResponse>;
      })
      .then((json) => setData(json))
      .catch((err: Error) => setError(err.message))
      .finally(() => setIsLoading(false));
  }, [q]);

  const handleSearch = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!query.trim()) return;
    router.push(`/results?q=${encodeURIComponent(query.trim())}`);
  };

  return (
    <div>
      <div className="mb-10">
        <p className="text-sm text-indigo-600 dark:text-indigo-400 font-medium mb-1 uppercase tracking-wide">
          Analysis Results
        </p>
        <h2 className="text-3xl font-bold text-slate-900 dark:text-white mb-6 leading-snug">
          {q ? (
            <>
              Results for:{" "}
              <span className="text-indigo-600 dark:text-indigo-400">
                &ldquo;{q}&rdquo;
              </span>
            </>
          ) : (
            "No topic provided"
          )}
        </h2>

        <form onSubmit={handleSearch} className="flex gap-3 max-w-2xl">
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search another topic…"
            className="flex-1 rounded-xl border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800 px-4 py-3 text-sm text-slate-900 dark:text-white placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent shadow-sm"
          />
          <button
            type="submit"
            disabled={!query.trim() || isLoading}
            className="rounded-xl bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white font-semibold px-6 py-3 text-sm shadow-sm transition-all"
          >
            Analyze
          </button>
        </form>
      </div>

      {!q && <EmptyState />}
      {q && isLoading && <LoadingState />}
      {q && error && <ErrorCard message={error} />}

      {q && data && !isLoading && (
        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-6">
          <ResultSection
            icon="🧬"
            title="Research Landscape"
            color="blue"
            items={data.landscape}
            itemType="topic"
          />
          <ResultSection
            icon="🚀"
            title="Emerging Areas"
            color="purple"
            items={data.emergingAreas}
            itemType="area"
          />
          <ResultSection
            icon="🔍"
            title="Research Gaps"
            color="indigo"
            items={data.researchGaps}
            itemType="gap"
          />
          <ResultSection
            icon="💡"
            title="Suggested Projects"
            color="emerald"
            items={data.projects}
            itemType="project"
          />
          <ResultSection
            icon="🗄️"
            title="Dataset Recommendations"
            color="violet"
            items={data.datasets}
            itemType="dataset"
          />
          <PapersSection papers={data.papers} />
        </div>
      )}
    </div>
  );
}

// ─── Related Papers card ──────────────────────────────────────────────────────

function PapersSection({ papers }: { papers: Paper[] }) {
  return (
    <div className="rounded-2xl border border-slate-200 dark:border-slate-700 bg-white/80 dark:bg-slate-800/60 overflow-hidden shadow-sm backdrop-blur-sm">
      <div className="bg-rose-600 px-5 py-4 flex items-center gap-2">
        <span className="text-xl">📚</span>
        <h3 className="font-semibold text-white text-base">Related Papers</h3>
        <span className="ml-auto text-xs font-medium px-2 py-0.5 rounded-full bg-rose-100 text-rose-700 dark:bg-rose-900/40 dark:text-rose-300">
          {papers.length} found
        </span>
      </div>

      {papers.length === 0 ? (
        <div className="px-5 py-8 text-center text-sm text-slate-400 dark:text-slate-500">
          No papers found for this topic.
        </div>
      ) : (
        <ul className="divide-y divide-slate-100 dark:divide-slate-700/50">
          {papers.map((paper) => (
            <PaperItem key={paper.pmid} paper={paper} />
          ))}
        </ul>
      )}

      <div className="px-5 py-3 border-t border-slate-100 dark:border-slate-700/50">
        <p className="text-xs text-slate-400 dark:text-slate-500 italic">
          Live data — NCBI ESearch · ESummary · EFetch
        </p>
      </div>
    </div>
  );
}

function PaperItem({ paper }: { paper: Paper }) {
  const displayAuthors =
    paper.authors.slice(0, 3).join(", ") +
    (paper.authors.length > 3 ? " et al." : "");

  const abstractPreview = paper.abstract
    ? paper.abstract.length > 300
      ? paper.abstract.slice(0, 297) + "…"
      : paper.abstract
    : null;

  return (
    <li className="px-5 py-4 flex gap-3 items-start">
      <span className="mt-1.5 h-2 w-2 rounded-full shrink-0 bg-rose-500" />
      <div className="min-w-0 space-y-1">
        <p className="text-sm font-medium text-slate-800 dark:text-slate-200 leading-snug">
          {paper.title}
        </p>

        <p className="text-xs text-slate-500 dark:text-slate-400">
          {displayAuthors}
        </p>

        <p className="text-xs text-slate-500 dark:text-slate-400">
          <span className="font-medium">{paper.journal}</span>
          {" · "}
          {paper.year}
        </p>

        {abstractPreview && (
          <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed pt-0.5">
            {abstractPreview}
          </p>
        )}

        <div className="flex flex-wrap gap-2 pt-1">
          {paper.publicationTypes?.slice(0, 2).map((t) => (
            <span
              key={t}
              className="text-xs bg-slate-100 dark:bg-slate-700 text-slate-500 dark:text-slate-400 px-2 py-0.5 rounded-full"
            >
              {t}
            </span>
          ))}
          {paper.doi && (
            <span className="text-xs bg-slate-100 dark:bg-slate-700 text-slate-500 dark:text-slate-400 px-2 py-0.5 rounded-full font-mono">
              DOI: {paper.doi}
            </span>
          )}
          <a
            href={paper.pubmedUrl ?? `https://pubmed.ncbi.nlm.nih.gov/${paper.pmid}/`}
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs bg-rose-50 dark:bg-rose-900/30 text-rose-600 dark:text-rose-400 px-2 py-0.5 rounded-full hover:underline"
          >
            PMID {paper.pmid} ↗
          </a>
        </div>

        {paper.meshTerms && paper.meshTerms.length > 0 && (
          <div className="flex flex-wrap gap-1 pt-0.5">
            {paper.meshTerms.slice(0, 4).map((term) => (
              <span
                key={term}
                className="text-xs bg-indigo-50 dark:bg-indigo-900/20 text-indigo-600 dark:text-indigo-400 px-2 py-0.5 rounded-full"
              >
                {term}
              </span>
            ))}
            {paper.meshTerms.length > 4 && (
              <span className="text-xs text-slate-400 dark:text-slate-500 px-1 py-0.5">
                +{paper.meshTerms.length - 4} more
              </span>
            )}
          </div>
        )}
      </div>
    </li>
  );
}

// ─── Shared components ────────────────────────────────────────────────────────

function LoadingState() {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-6 animate-pulse">
      {[...Array(6)].map((_, i) => (
        <div
          key={i}
          className="rounded-2xl border border-slate-200 dark:border-slate-700 overflow-hidden"
        >
          <div className="h-14 bg-slate-300 dark:bg-slate-600" />
          <div className="p-5 space-y-3">
            {[...Array(3)].map((_, j) => (
              <div key={j} className="h-4 bg-slate-200 dark:bg-slate-700 rounded" />
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

function ErrorCard({ message }: { message: string }) {
  return (
    <div className="rounded-2xl border border-red-200 dark:border-red-800 bg-red-50 dark:bg-red-900/20 p-8 text-center max-w-lg mx-auto">
      <div className="text-4xl mb-3">⚠️</div>
      <h3 className="text-lg font-semibold text-red-700 dark:text-red-400 mb-2">
        Analysis failed
      </h3>
      <p className="text-sm text-red-600 dark:text-red-500">{message}</p>
      <p className="text-xs text-red-400 dark:text-red-600 mt-3">
        Please try again or search for a different topic.
      </p>
    </div>
  );
}

function EmptyState() {
  return (
    <div className="flex flex-col items-center justify-center py-24 text-center">
      <div className="text-6xl mb-4">🔬</div>
      <h3 className="text-xl font-semibold text-slate-700 dark:text-slate-300 mb-2">
        No topic entered
      </h3>
      <p className="text-slate-500 dark:text-slate-400 mb-6">
        Go back to the homepage and enter a research topic to analyze.
      </p>
      <a
        href="/"
        className="rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-semibold px-6 py-3 text-sm shadow-sm transition-all"
      >
        Go to Homepage
      </a>
    </div>
  );
}

function ResultSection({
  icon,
  title,
  color,
  items,
  itemType,
}: {
  icon: string;
  title: string;
  color: "blue" | "purple" | "indigo" | "emerald" | "violet";
  items: string[];
  itemType: string;
}) {
  const colorMap = {
    blue: {
      header: "bg-blue-600",
      badge: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300",
      bullet: "bg-blue-500",
    },
    purple: {
      header: "bg-purple-600",
      badge: "bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300",
      bullet: "bg-purple-500",
    },
    indigo: {
      header: "bg-indigo-600",
      badge: "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/40 dark:text-indigo-300",
      bullet: "bg-indigo-500",
    },
    emerald: {
      header: "bg-emerald-600",
      badge: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300",
      bullet: "bg-emerald-500",
    },
    violet: {
      header: "bg-violet-600",
      badge: "bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300",
      bullet: "bg-violet-500",
    },
  };

  const c = colorMap[color];

  return (
    <div className="rounded-2xl border border-slate-200 dark:border-slate-700 bg-white/80 dark:bg-slate-800/60 overflow-hidden shadow-sm backdrop-blur-sm">
      <div className={`${c.header} px-5 py-4 flex items-center gap-2`}>
        <span className="text-xl">{icon}</span>
        <h3 className="font-semibold text-white text-base">{title}</h3>
        <span className={`ml-auto text-xs font-medium px-2 py-0.5 rounded-full ${c.badge}`}>
          {items.length} found
        </span>
      </div>
      <ul className="divide-y divide-slate-100 dark:divide-slate-700/50">
        {items.map((item, i) => (
          <li key={i} className="px-5 py-4 flex gap-3 items-start">
            <span className={`mt-1.5 h-2 w-2 rounded-full shrink-0 ${c.bullet}`} />
            <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{item}</p>
          </li>
        ))}
      </ul>
      <div className="px-5 py-3 border-t border-slate-100 dark:border-slate-700/50">
        <p className="text-xs text-slate-400 dark:text-slate-500 italic">
          Powered by AI — {itemType}s generated for your query
        </p>
      </div>
    </div>
  );
}
