"use client";

import { useSearchParams, useRouter } from "next/navigation";
import { useState, useEffect, useRef, FormEvent } from "react";
import type { Paper } from "@/types/paper";
import type { Dataset } from "@/types/dataset";
import type { SequenceResource } from "@/types/sequence-resource";
import type { GeneRecord } from "@/types/gene-record";
import type { NormalizedQuery } from "@/types/normalized-query";
import { toConfidenceTier } from "@/types/query-resolution";
import GeneExplorerSection from "@/components/GeneExplorerSection";

// TODO: OpenAI integration — landscape, emergingAreas, researchGaps, and projects
// will be generated by GPT-4 using the query + PubMed abstracts + GEO summaries as context.

// TODO: PubMed pipeline is live (ESearch → ESummary + EFetch in parallel).
// TODO: GEO pipeline is live (ESearch → ESummary → Dataset[]).
// Future: supplement with SRA, ArrayExpress, TCGA, Europe PMC.

// ─── Shared API types ─────────────────────────────────────────────────────────

interface PaginationMeta {
  totalCount: number;
  pageSize: number;
  offset: number;
  hasMore: boolean;
  nextOffset: number | null;
  currentPage: number;
  totalPages: number;
  hitUpstreamLimit: boolean;
}

interface AnalysisResponse {
  landscape: string[];
  emergingAreas: string[];
  researchGaps: string[];
  projects: string[];
  papers: Paper[];
  papersMeta: PaginationMeta | null;
  datasets: Dataset[];
  datasetsMeta: PaginationMeta | null;
  papersError?: string;
  datasetsError?: string;
  /** Sequence resources — populated on initial load only; empty on Load More requests. */
  sequences: SequenceResource[];
  sequencesError?: string;
  /** Gene records for this page. Populated on initial load and gene pagination. */
  genes: GeneRecord[];
  genesMeta: PaginationMeta | null;
  genesError?: string;
  /**
   * Structured result of the Biological Query Resolution Layer (Phase 5.1.5).
   * Populated on the initial load only — null on Load More requests.
   */
  resolution: NormalizedQuery | null;
  /**
   * The query string actually passed to PubMed, GEO, and Sequence Foundation.
   * Equals normalizedQuery for HIGH-confidence resolutions; equals originalQuery otherwise.
   * Pass back as `resolvedQuery` on Load More requests.
   */
  effectiveQuery: string;
}

// ─── Main component ───────────────────────────────────────────────────────────

export default function ResultsContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const q = searchParams.get("q") ?? "";

  const [query, setQuery] = useState(q);

  // Static content (AI cards) — only set on initial load
  const [staticData, setStaticData] = useState<Pick<
    AnalysisResponse,
    "landscape" | "emergingAreas" | "researchGaps" | "projects"
  > | null>(null);

  // Initial load state
  const [initialLoading, setInitialLoading] = useState(false);
  const [initialError, setInitialError] = useState<string | null>(null);
  const [initialLoaded, setInitialLoaded] = useState(false);

  // ── Papers state ──────────────────────────────────────────────────────────
  const [papers, setPapers] = useState<Paper[]>([]);
  const [papersMeta, setPapersMeta] = useState<PaginationMeta | null>(null);
  const [papersLoading, setPapersLoading] = useState(false);
  // papersPageError: only the latest failed Load More — page 1 results remain visible
  const [papersPageError, setPapersPageError] = useState<string | null>(null);
  // The nextOffset to retry when papersPageError is set
  const papersRetryOffset = useRef<number | null>(null);

  // ── Datasets state ────────────────────────────────────────────────────────
  const [datasets, setDatasets] = useState<Dataset[]>([]);
  const [datasetsMeta, setDatasetsMeta] = useState<PaginationMeta | null>(null);
  const [datasetsLoading, setDatasetsLoading] = useState(false);
  const [datasetsPageError, setDatasetsPageError] = useState<string | null>(null);
  const datasetsRetryOffset = useRef<number | null>(null);

  // ── Sequence state (initial load only — no pagination in Phase 5.1) ───────
  const [sequences, setSequences] = useState<SequenceResource[]>([]);
  const [sequencesError, setSequencesError] = useState<string | undefined>(undefined);

  // ── Gene Explorer state (Phase 5.2) ───────────────────────────────────────
  const [genes, setGenes] = useState<GeneRecord[]>([]);
  const [genesMeta, setGenesMeta] = useState<PaginationMeta | null>(null);
  const [genesLoading, setGenesLoading] = useState(false);
  const [genesPageError, setGenesPageError] = useState<string | null>(null);
  const [genesError, setGenesError] = useState<string | undefined>(undefined);
  const genesRetryOffset = useRef<number | null>(null);

  // ── Biological Query Resolution state (Phase 5.1.5) ───────────────────────
  // Populated on initial load only. Reset when the user submits a new query.
  const [resolution, setResolution] = useState<NormalizedQuery | null>(null);
  /**
   * The query string that was actually used for the initial load (may differ from `q`
   * when the resolver produced a HIGH-confidence normalized form).
   * Passed back to the server on Load More requests so pagination stays aligned.
   */
  const [effectiveQuery, setEffectiveQuery] = useState<string>("");

  // ── Initial load ──────────────────────────────────────────────────────────
  useEffect(() => {
    if (!q.trim()) return;

    setInitialLoading(true);
    setInitialError(null);
    setInitialLoaded(false);
    setStaticData(null);
    setPapers([]);
    setPapersMeta(null);
    setDatasets([]);
    setDatasetsMeta(null);
    setPapersPageError(null);
    setDatasetsPageError(null);
    setSequences([]);
    setSequencesError(undefined);
    setGenes([]);
    setGenesMeta(null);
    setGenesPageError(null);
    setGenesError(undefined);
    setResolution(null);
    setEffectiveQuery(q);

    fetch("/api/analyze", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ query: q, limit: 10 }),
    })
      .then((res) => {
        if (!res.ok) throw new Error(`Server error: ${res.status}`);
        return res.json() as Promise<AnalysisResponse>;
      })
      .then((json) => {
        setStaticData({
          landscape: json.landscape,
          emergingAreas: json.emergingAreas,
          researchGaps: json.researchGaps,
          projects: json.projects,
        });
        setPapers(json.papers);
        setPapersMeta(json.papersMeta);
        setDatasets(json.datasets);
        setDatasetsMeta(json.datasetsMeta);
        setSequences(json.sequences ?? []);
        setSequencesError(json.sequencesError);
        setGenes(json.genes ?? []);
        setGenesMeta(json.genesMeta ?? null);
        setGenesError(json.genesError);
        setResolution(json.resolution ?? null);
        // Track effectiveQuery so Load More sends the same query that produced page 1.
        setEffectiveQuery(json.effectiveQuery ?? q);
        setInitialLoaded(true);
      })
      .catch((err: Error) => setInitialError(err.message))
      .finally(() => setInitialLoading(false));
  }, [q]);

  // ── Load More Papers ──────────────────────────────────────────────────────
  const loadMorePapers = async (offsetOverride?: number) => {
    // Guard: do not fire while another papers request is in flight.
    // This enforces the spec requirement: "a user physically cannot fire overlapping requests."
    if (papersLoading) return;

    const nextOffset = offsetOverride ?? papersMeta?.nextOffset;
    if (nextOffset == null) return;

    setPapersLoading(true);
    setPapersPageError(null);
    papersRetryOffset.current = nextOffset;

    try {
      const res = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          query: q,
          limit: 10,
          papersOffset: nextOffset,
          datasetsOffset: 0, // ensures server runs only PubMed
          // Pass back the effectiveQuery from the initial load so pagination uses
          // the same query that produced page 1 (respects HIGH-confidence normalization).
          resolvedQuery: effectiveQuery !== q ? effectiveQuery : undefined,
        }),
      });
      if (!res.ok) throw new Error(`Server error: ${res.status}`);
      const json = (await res.json()) as AnalysisResponse;

      const newPapers = json.papers ?? [];

      // ── Deduplication: papers by PMID ────────────────────────────────────
      // If the upstream API returns overlapping records across page boundaries,
      // or a retry returns the same page twice, only append previously unseen records.
      setPapers((prev) => {
        const seenPmids = new Set(prev.map((p) => p.pmid));
        const uniqueNew = newPapers.filter((p) => !seenPmids.has(p.pmid));
        return [...prev, ...uniqueNew];
      });

      if (json.papersMeta) setPapersMeta(json.papersMeta);
      papersRetryOffset.current = null;
    } catch (err) {
      // Step 9: previously loaded results remain visible; only this request shows the error.
      // The retry button will re-attempt from the same offset.
      setPapersPageError(err instanceof Error ? err.message : String(err));
    } finally {
      setPapersLoading(false);
    }
  };

  // ── Load More Genes ───────────────────────────────────────────────────────
  const loadMoreGenes = async (offsetOverride?: number) => {
    if (genesLoading) return;

    const nextOffset = offsetOverride ?? genesMeta?.nextOffset;
    if (nextOffset == null) return;

    setGenesLoading(true);
    setGenesPageError(null);
    genesRetryOffset.current = nextOffset;

    try {
      const res = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          query: q,
          limit: 10,
          genesOffset: nextOffset,
          papersOffset: 0,
          datasetsOffset: 0,
          resolvedQuery: effectiveQuery !== q ? effectiveQuery : undefined,
        }),
      });
      if (!res.ok) throw new Error(`Server error: ${res.status}`);
      const json = (await res.json()) as AnalysisResponse;

      const newGenes = json.genes ?? [];

      setGenes((prev) => {
        const seenIds = new Set(prev.map((g) => g.geneId));
        const uniqueNew = newGenes.filter((g) => !seenIds.has(g.geneId));
        return [...prev, ...uniqueNew];
      });

      if (json.genesMeta) setGenesMeta(json.genesMeta);
      genesRetryOffset.current = null;
    } catch (err) {
      setGenesPageError(err instanceof Error ? err.message : String(err));
    } finally {
      setGenesLoading(false);
    }
  };

  // ── Load More Datasets ────────────────────────────────────────────────────
  const loadMoreDatasets = async (offsetOverride?: number) => {
    if (datasetsLoading) return;

    const nextOffset = offsetOverride ?? datasetsMeta?.nextOffset;
    if (nextOffset == null) return;

    setDatasetsLoading(true);
    setDatasetsPageError(null);
    datasetsRetryOffset.current = nextOffset;

    try {
      const res = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          query: q,
          limit: 10,
          datasetsOffset: nextOffset,
          papersOffset: 0, // ensures server runs only GEO
          // Pass back the effectiveQuery from the initial load so pagination uses
          // the same query that produced page 1 (respects HIGH-confidence normalization).
          resolvedQuery: effectiveQuery !== q ? effectiveQuery : undefined,
        }),
      });
      if (!res.ok) throw new Error(`Server error: ${res.status}`);
      const json = (await res.json()) as AnalysisResponse;

      const newDatasets = json.datasets ?? [];

      // ── Deduplication: datasets by accession (GSE ID) ────────────────────
      setDatasets((prev) => {
        const seenAccessions = new Set(prev.map((d) => d.accession));
        const uniqueNew = newDatasets.filter((d) => !seenAccessions.has(d.accession));
        return [...prev, ...uniqueNew];
      });

      if (json.datasetsMeta) setDatasetsMeta(json.datasetsMeta);
      datasetsRetryOffset.current = null;
    } catch (err) {
      setDatasetsPageError(err instanceof Error ? err.message : String(err));
    } finally {
      setDatasetsLoading(false);
    }
  };

  const handleSearch = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!query.trim()) return;
    router.push(`/results?q=${encodeURIComponent(query.trim())}`);
  };

  return (
    <div>
      <div className="mb-10">
        <p className="text-sm text-indigo-600 dark:text-indigo-400 font-medium mb-1 uppercase tracking-wide">
          Analysis Results
        </p>
        <h2 className="text-3xl font-bold text-slate-900 dark:text-white mb-6 leading-snug">
          {q ? (
            <>
              Results for:{" "}
              <span className="text-indigo-600 dark:text-indigo-400">
                &ldquo;{q}&rdquo;
              </span>
            </>
          ) : (
            "No topic provided"
          )}
        </h2>

        <form onSubmit={handleSearch} className="flex gap-3 max-w-2xl">
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search another topic…"
            className="flex-1 rounded-xl border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800 px-4 py-3 text-sm text-slate-900 dark:text-white placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent shadow-sm"
          />
          <button
            type="submit"
            disabled={!query.trim() || initialLoading}
            className="rounded-xl bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white font-semibold px-6 py-3 text-sm shadow-sm transition-all"
          >
            Analyze
          </button>
        </form>
      </div>

      {!q && <EmptyState />}
      {q && initialLoading && <LoadingState />}
      {q && initialError && <ErrorCard message={initialError} />}

      {q && initialLoaded && staticData && (
        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-6">
          {/* Biological Query Resolution card — full-width, always first */}
          <div className="col-span-1 sm:col-span-2 xl:col-span-3">
            <QueryResolutionCard resolution={resolution} originalQuery={q} />
          </div>

          <ResultSection
            icon="🧬"
            title="Research Landscape"
            color="blue"
            items={staticData.landscape}
            itemType="topic"
          />
          <ResultSection
            icon="🚀"
            title="Emerging Areas"
            color="purple"
            items={staticData.emergingAreas}
            itemType="area"
          />
          <ResultSection
            icon="🔍"
            title="Research Gaps"
            color="indigo"
            items={staticData.researchGaps}
            itemType="gap"
          />
          <ResultSection
            icon="💡"
            title="Suggested Projects"
            color="emerald"
            items={staticData.projects}
            itemType="project"
          />

          <SequenceSection
            sequences={sequences}
            sequencesError={sequencesError}
          />

          <GeneExplorerSection
            genes={genes}
            meta={genesMeta}
            isLoading={genesLoading}
            pageError={genesPageError}
            retryOffset={genesRetryOffset.current}
            genesError={genesError}
            onLoadMore={() => loadMoreGenes()}
            onRetry={(offset) => loadMoreGenes(offset)}
          />

          <DatasetsSection
            datasets={datasets}
            meta={datasetsMeta}
            isLoading={datasetsLoading}
            pageError={datasetsPageError}
            retryOffset={datasetsRetryOffset.current}
            onLoadMore={() => loadMoreDatasets()}
            onRetry={(offset) => loadMoreDatasets(offset)}
          />

          <PapersSection
            papers={papers}
            meta={papersMeta}
            isLoading={papersLoading}
            pageError={papersPageError}
            retryOffset={papersRetryOffset.current}
            onLoadMore={() => loadMorePapers()}
            onRetry={(offset) => loadMorePapers(offset)}
          />
        </div>
      )}
    </div>
  );
}

// ─── Result summary line ──────────────────────────────────────────────────────

function ResultSummary({
  label,
  meta,
  shownCount,
}: {
  label: string;
  meta: PaginationMeta | null;
  shownCount: number;
}) {
  if (!meta) return null;

  const from = 1;
  const to = shownCount;
  const total = meta.totalCount.toLocaleString();

  return (
    <p className="text-xs text-slate-400 dark:text-slate-500 px-5 py-2 border-b border-slate-100 dark:border-slate-700/50">
      {label} — <span className="font-medium text-slate-600 dark:text-slate-300">{total}</span>{" "}
      found — Showing {from}–{to}
    </p>
  );
}

// ─── Load More / end-state footer ────────────────────────────────────────────

function ExplorationFooter({
  meta,
  isLoading,
  pageError,
  retryOffset,
  onLoadMore,
  onRetry,
  accentColor,
  dataLabel,
}: {
  meta: PaginationMeta | null;
  isLoading: boolean;
  pageError: string | null;
  retryOffset: number | null;
  onLoadMore: () => void;
  onRetry: (offset: number) => void;
  accentColor: string;
  dataLabel: string;
}) {
  // Step 9: if a page-N request failed, show inline error + retry for THAT page only.
  // Previously loaded records are not cleared.
  if (pageError) {
    return (
      <div className="px-5 py-4 border-t border-slate-100 dark:border-slate-700/50 space-y-2">
        <p className="text-xs text-amber-600 dark:text-amber-400 font-medium">
          ⚠️ Failed to load next page — previous results preserved.
        </p>
        <p className="text-xs text-slate-500 dark:text-slate-400">{pageError}</p>
        {retryOffset !== null && (
          <button
            onClick={() => onRetry(retryOffset)}
            disabled={isLoading}
            className="text-xs bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 px-3 py-1.5 rounded-full hover:bg-amber-200 dark:hover:bg-amber-900/50 disabled:opacity-50 font-medium transition-colors"
          >
            {isLoading ? "Retrying…" : "Retry"}
          </button>
        )}
      </div>
    );
  }

  if (!meta) return null;

  // Step 8a: genuinely exhausted — no more records upstream.
  if (!meta.hasMore && !meta.hitUpstreamLimit) {
    return (
      <div className="px-5 py-3 border-t border-slate-100 dark:border-slate-700/50 text-center">
        <p className="text-xs text-slate-400 dark:text-slate-500">
          You&rsquo;ve reached the end of available {dataLabel}.
        </p>
      </div>
    );
  }

  // Step 8b: upstream ceiling hit — more records exist but cannot be paged further.
  if (!meta.hasMore && meta.hitUpstreamLimit) {
    return (
      <div className="px-5 py-3 border-t border-slate-100 dark:border-slate-700/50 text-center">
        <p className="text-xs text-amber-600 dark:text-amber-400 font-medium">
          Showing the first {meta.totalCount >= 9999 ? "~9,999" : meta.totalCount.toLocaleString()} of{" "}
          {meta.totalCount.toLocaleString()} results
        </p>
        <p className="text-xs text-slate-400 dark:text-slate-500 mt-0.5">
          Try narrowing your search for more specific results.
        </p>
      </div>
    );
  }

  // Load More is available.
  return (
    <div className="px-5 py-4 border-t border-slate-100 dark:border-slate-700/50 flex items-center justify-between">
      <button
        onClick={onLoadMore}
        // CRITICAL: disabled while in-flight — prevents overlapping requests (spec Step 6).
        disabled={isLoading}
        className={`text-xs font-semibold px-4 py-2 rounded-full transition-all disabled:opacity-50 ${accentColor}`}
      >
        {isLoading ? (
          <span className="flex items-center gap-2">
            <LoadingSpinner />
            Loading…
          </span>
        ) : (
          "Load More"
        )}
      </button>
      <p className="text-xs text-slate-400 dark:text-slate-500">
        {meta.totalCount.toLocaleString()} total
      </p>
    </div>
  );
}

function LoadingSpinner() {
  return (
    <svg
      className="animate-spin h-3 w-3"
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
    >
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
      <path
        className="opacity-75"
        fill="currentColor"
        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
      />
    </svg>
  );
}

// ─── Dataset Recommendations card ────────────────────────────────────────────

function DatasetsSection({
  datasets,
  meta,
  isLoading,
  pageError,
  retryOffset,
  onLoadMore,
  onRetry,
}: {
  datasets: Dataset[];
  meta: PaginationMeta | null;
  isLoading: boolean;
  pageError: string | null;
  retryOffset: number | null;
  onLoadMore: () => void;
  onRetry: (offset: number) => void;
}) {
  return (
    <div className="rounded-2xl border border-slate-200 dark:border-slate-700 bg-white/80 dark:bg-slate-800/60 overflow-hidden shadow-sm backdrop-blur-sm">
      <div className="bg-violet-600 px-5 py-4 flex items-center gap-2">
        <span className="text-xl">🗄️</span>
        <h3 className="font-semibold text-white text-base">Dataset Recommendations</h3>
        {isLoading && (
          <span className="ml-1 text-violet-200">
            <LoadingSpinner />
          </span>
        )}
        <span className="ml-auto text-xs font-medium px-2 py-0.5 rounded-full bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300">
          {datasets.length} shown
        </span>
      </div>

      <ResultSummary label="GEO" meta={meta} shownCount={datasets.length} />

      {datasets.length === 0 ? (
        <div className="px-5 py-8 text-center text-sm text-slate-400 dark:text-slate-500">
          No datasets found for this topic.
        </div>
      ) : (
        <ul className="divide-y divide-slate-100 dark:divide-slate-700/50">
          {datasets.map((ds) => (
            <DatasetItem key={ds.accession} dataset={ds} />
          ))}
        </ul>
      )}

      <ExplorationFooter
        meta={meta}
        isLoading={isLoading}
        pageError={pageError}
        retryOffset={retryOffset}
        onLoadMore={onLoadMore}
        onRetry={onRetry}
        accentColor="bg-violet-100 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300 hover:bg-violet-200 dark:hover:bg-violet-900/50"
        dataLabel="datasets"
      />

      <div className="px-5 py-3 border-t border-slate-100 dark:border-slate-700/50">
        <p className="text-xs text-slate-400 dark:text-slate-500 italic">
          Live data — NCBI GEO ESearch · ESummary · GSE Series
        </p>
      </div>
    </div>
  );
}

function DatasetItem({ dataset: ds }: { dataset: Dataset }) {
  const summaryPreview = ds.summary
    ? ds.summary.length > 200
      ? ds.summary.slice(0, 197) + "…"
      : ds.summary
    : null;

  const formattedDate = ds.publicationDate
    ? (() => {
        const d = new Date(ds.publicationDate + "T00:00:00Z");
        return isNaN(d.getTime())
          ? ds.publicationDate
          : d.toLocaleDateString("en-US", { month: "short", year: "numeric", timeZone: "UTC" });
      })()
    : null;

  const shortExperimentType = ds.experimentType
    ? ds.experimentType
        .replace("Expression profiling by high throughput sequencing", "RNA-Seq")
        .replace("Expression profiling by array", "Microarray")
        .replace("Genome binding/occupancy profiling by high throughput sequencing", "ChIP-Seq / ATAC-Seq")
        .replace("Methylation profiling by high throughput sequencing", "Methylation-Seq")
        .replace("Other", ds.experimentType)
    : null;

  const hasDownloads =
    ds.seriesMatrixUrl || ds.softFileUrl || ds.miniMLUrl || ds.ftpDownloadUrl;

  return (
    <li className="px-5 py-4 flex gap-3 items-start">
      <span className="mt-1.5 h-2 w-2 rounded-full shrink-0 bg-violet-500" />
      <div className="min-w-0 space-y-1.5">
        <p className="text-sm font-medium text-slate-800 dark:text-slate-200 leading-snug">
          {ds.title}
        </p>

        {summaryPreview && (
          <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
            {summaryPreview}
          </p>
        )}

        <div className="flex flex-wrap gap-2 pt-0.5">
          <span className="text-xs bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300 px-2 py-0.5 rounded-full font-mono font-medium">
            {ds.accession}
          </span>
          <span className="text-xs bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 px-2 py-0.5 rounded-full">
            🧬 {ds.organism}
          </span>
          <span className="text-xs bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 px-2 py-0.5 rounded-full font-mono">
            {ds.platform}
          </span>
          {ds.sampleCount !== undefined && (
            <span className="text-xs bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 px-2 py-0.5 rounded-full">
              {ds.sampleCount} samples
            </span>
          )}
          {shortExperimentType && (
            <span className="text-xs bg-indigo-50 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 px-2 py-0.5 rounded-full">
              {shortExperimentType}
            </span>
          )}
          {formattedDate && (
            <span className="text-xs bg-slate-100 dark:bg-slate-700 text-slate-500 dark:text-slate-400 px-2 py-0.5 rounded-full">
              {formattedDate}
            </span>
          )}
        </div>

        <div className="flex flex-wrap gap-2 pt-0.5">
          {ds.geoUrl && (
            <a
              href={ds.geoUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs bg-violet-50 dark:bg-violet-900/30 text-violet-600 dark:text-violet-400 px-2 py-0.5 rounded-full hover:underline"
            >
              GEO ↗
            </a>
          )}
          {hasDownloads && (
            <>
              {ds.seriesMatrixUrl && (
                <a
                  href={ds.seriesMatrixUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 px-2 py-0.5 rounded-full hover:underline"
                >
                  Series Matrix ↓
                </a>
              )}
              {ds.softFileUrl && (
                <a
                  href={ds.softFileUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 px-2 py-0.5 rounded-full hover:underline"
                >
                  SOFT ↓
                </a>
              )}
              {ds.miniMLUrl && (
                <a
                  href={ds.miniMLUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 px-2 py-0.5 rounded-full hover:underline"
                >
                  MINiML ↓
                </a>
              )}
              {ds.ftpDownloadUrl && (
                <a
                  href={ds.ftpDownloadUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 px-2 py-0.5 rounded-full hover:underline"
                >
                  FTP ↗
                </a>
              )}
            </>
          )}
          {ds.pubmedIds && ds.pubmedIds.length > 0 && (
            <a
              href={`https://pubmed.ncbi.nlm.nih.gov/${ds.pubmedIds[0]}/`}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs bg-rose-50 dark:bg-rose-900/30 text-rose-600 dark:text-rose-400 px-2 py-0.5 rounded-full hover:underline"
            >
              PMID {ds.pubmedIds[0]} ↗
            </a>
          )}
        </div>
      </div>
    </li>
  );
}

// ─── Related Papers card ──────────────────────────────────────────────────────

function PapersSection({
  papers,
  meta,
  isLoading,
  pageError,
  retryOffset,
  onLoadMore,
  onRetry,
}: {
  papers: Paper[];
  meta: PaginationMeta | null;
  isLoading: boolean;
  pageError: string | null;
  retryOffset: number | null;
  onLoadMore: () => void;
  onRetry: (offset: number) => void;
}) {
  return (
    <div className="rounded-2xl border border-slate-200 dark:border-slate-700 bg-white/80 dark:bg-slate-800/60 overflow-hidden shadow-sm backdrop-blur-sm">
      <div className="bg-rose-600 px-5 py-4 flex items-center gap-2">
        <span className="text-xl">📚</span>
        <h3 className="font-semibold text-white text-base">Related Papers</h3>
        {isLoading && (
          <span className="ml-1 text-rose-200">
            <LoadingSpinner />
          </span>
        )}
        <span className="ml-auto text-xs font-medium px-2 py-0.5 rounded-full bg-rose-100 text-rose-700 dark:bg-rose-900/40 dark:text-rose-300">
          {papers.length} shown
        </span>
      </div>

      <ResultSummary label="PubMed" meta={meta} shownCount={papers.length} />

      {papers.length === 0 ? (
        <div className="px-5 py-8 text-center text-sm text-slate-400 dark:text-slate-500">
          No papers found for this topic.
        </div>
      ) : (
        <ul className="divide-y divide-slate-100 dark:divide-slate-700/50">
          {papers.map((paper) => (
            <PaperItem key={paper.pmid} paper={paper} />
          ))}
        </ul>
      )}

      <ExplorationFooter
        meta={meta}
        isLoading={isLoading}
        pageError={pageError}
        retryOffset={retryOffset}
        onLoadMore={onLoadMore}
        onRetry={onRetry}
        accentColor="bg-rose-100 dark:bg-rose-900/30 text-rose-700 dark:text-rose-300 hover:bg-rose-200 dark:hover:bg-rose-900/50"
        dataLabel="papers"
      />

      <div className="px-5 py-3 border-t border-slate-100 dark:border-slate-700/50">
        <p className="text-xs text-slate-400 dark:text-slate-500 italic">
          Live data — NCBI ESearch · ESummary · EFetch
        </p>
      </div>
    </div>
  );
}

function PaperItem({ paper }: { paper: Paper }) {
  const displayAuthors =
    paper.authors.slice(0, 3).join(", ") +
    (paper.authors.length > 3 ? " et al." : "");

  const abstractPreview = paper.abstract
    ? paper.abstract.length > 300
      ? paper.abstract.slice(0, 297) + "…"
      : paper.abstract
    : null;

  return (
    <li className="px-5 py-4 flex gap-3 items-start">
      <span className="mt-1.5 h-2 w-2 rounded-full shrink-0 bg-rose-500" />
      <div className="min-w-0 space-y-1">
        <p className="text-sm font-medium text-slate-800 dark:text-slate-200 leading-snug">
          {paper.title}
        </p>
        <p className="text-xs text-slate-500 dark:text-slate-400">{displayAuthors}</p>
        <p className="text-xs text-slate-500 dark:text-slate-400">
          <span className="font-medium">{paper.journal}</span>
          {" · "}
          {paper.year}
        </p>

        {abstractPreview && (
          <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed pt-0.5">
            {abstractPreview}
          </p>
        )}

        <div className="flex flex-wrap gap-2 pt-1">
          {paper.publicationTypes?.slice(0, 2).map((t) => (
            <span
              key={t}
              className="text-xs bg-slate-100 dark:bg-slate-700 text-slate-500 dark:text-slate-400 px-2 py-0.5 rounded-full"
            >
              {t}
            </span>
          ))}
          {paper.doi && (
            <span className="text-xs bg-slate-100 dark:bg-slate-700 text-slate-500 dark:text-slate-400 px-2 py-0.5 rounded-full font-mono">
              DOI: {paper.doi}
            </span>
          )}
          <a
            href={paper.pubmedUrl ?? `https://pubmed.ncbi.nlm.nih.gov/${paper.pmid}/`}
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs bg-rose-50 dark:bg-rose-900/30 text-rose-600 dark:text-rose-400 px-2 py-0.5 rounded-full hover:underline"
          >
            PMID {paper.pmid} ↗
          </a>
        </div>

        {paper.meshTerms && paper.meshTerms.length > 0 && (
          <div className="flex flex-wrap gap-1 pt-0.5">
            {paper.meshTerms.slice(0, 4).map((term) => (
              <span
                key={term}
                className="text-xs bg-indigo-50 dark:bg-indigo-900/20 text-indigo-600 dark:text-indigo-400 px-2 py-0.5 rounded-full"
              >
                {term}
              </span>
            ))}
            {paper.meshTerms.length > 4 && (
              <span className="text-xs text-slate-400 dark:text-slate-500 px-1 py-0.5">
                +{paper.meshTerms.length - 4} more
              </span>
            )}
          </div>
        )}
      </div>
    </li>
  );
}

// ─── Shared components ────────────────────────────────────────────────────────

function LoadingState() {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-6 animate-pulse">
      {[...Array(6)].map((_, i) => (
        <div
          key={i}
          className="rounded-2xl border border-slate-200 dark:border-slate-700 overflow-hidden"
        >
          <div className="h-14 bg-slate-300 dark:bg-slate-600" />
          <div className="p-5 space-y-3">
            {[...Array(3)].map((_, j) => (
              <div key={j} className="h-4 bg-slate-200 dark:bg-slate-700 rounded" />
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

function ErrorCard({ message }: { message: string }) {
  return (
    <div className="rounded-2xl border border-red-200 dark:border-red-800 bg-red-50 dark:bg-red-900/20 p-8 text-center max-w-lg mx-auto">
      <div className="text-4xl mb-3">⚠️</div>
      <h3 className="text-lg font-semibold text-red-700 dark:text-red-400 mb-2">
        Analysis failed
      </h3>
      <p className="text-sm text-red-600 dark:text-red-500">{message}</p>
      <p className="text-xs text-red-400 dark:text-red-600 mt-3">
        Please try again or search for a different topic.
      </p>
    </div>
  );
}

function EmptyState() {
  return (
    <div className="flex flex-col items-center justify-center py-24 text-center">
      <div className="text-6xl mb-4">🔬</div>
      <h3 className="text-xl font-semibold text-slate-700 dark:text-slate-300 mb-2">
        No topic entered
      </h3>
      <p className="text-slate-500 dark:text-slate-400 mb-6">
        Go back to the homepage and enter a research topic to analyze.
      </p>
      <a
        href="/"
        className="rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-semibold px-6 py-3 text-sm shadow-sm transition-all"
      >
        Go to Homepage
      </a>
    </div>
  );
}

// ─── Sequence Foundation card ─────────────────────────────────────────────────

const REF_STATUS_CONFIG: Record<string, { label: string; cls: string }> = {
  "reference genome": {
    label: "NCBI Reference Genome",
    cls: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300",
  },
  "representative genome": {
    label: "NCBI Representative Genome",
    cls: "bg-sky-100 text-sky-700 dark:bg-sky-900/40 dark:text-sky-300",
  },
  "refseq-gene": {
    label: "RefSeq Gene",
    cls: "bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300",
  },
  "refseq-chromosome": {
    label: "RefSeq",
    cls: "bg-sky-100 text-sky-700 dark:bg-sky-900/40 dark:text-sky-300",
  },
  "other assembly": {
    label: "Other Assembly",
    cls: "bg-slate-100 text-slate-600 dark:bg-slate-700 dark:text-slate-300",
  },
  "no-refseq": {
    label: "GenBank Only",
    cls: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300",
  },
};

const RULE_LABEL: Record<string, string> = {
  rule1: "accession lookup",
  rule2: "organism / assembly",
  rule3: "gene symbol",
};

function SequenceSection({
  sequences,
  sequencesError,
}: {
  sequences: SequenceResource[];
  sequencesError?: string;
}) {
  const seq = sequences[0];
  const statusCfg = seq?.referenceStatus ? REF_STATUS_CONFIG[seq.referenceStatus] : undefined;

  return (
    <div className="rounded-2xl border border-slate-200 dark:border-slate-700 bg-white/80 dark:bg-slate-800/60 overflow-hidden shadow-sm backdrop-blur-sm">
      {/* Header */}
      <div className="bg-teal-600 px-5 py-4 flex items-center gap-2">
        <span className="text-xl">🔬</span>
        <h3 className="font-semibold text-white text-base">Sequence Foundation</h3>
        <span className="ml-auto text-xs font-medium px-2 py-0.5 rounded-full bg-teal-100 text-teal-800 dark:bg-teal-900/40 dark:text-teal-200">
          {sequences.length > 0 ? `${sequences.length} resource` : "—"}
        </span>
      </div>

      {/* Error state */}
      {sequencesError && sequences.length === 0 && (
        <div className="px-5 py-6 text-sm text-amber-600 dark:text-amber-400">
          ⚠️ {sequencesError}
        </div>
      )}

      {/* Empty state */}
      {!sequencesError && sequences.length === 0 && (
        <div className="px-5 py-8 text-center text-sm text-slate-400 dark:text-slate-500">
          No sequence resources found for this query.
        </div>
      )}

      {/* Primary resource */}
      {seq && (
        <div className="px-5 py-4 space-y-3">
          {/* Accession + status badges */}
          <div className="flex flex-wrap gap-1.5 items-center">
            <span className="text-xs font-mono font-semibold bg-teal-50 dark:bg-teal-900/30 text-teal-700 dark:text-teal-300 px-2 py-0.5 rounded-full">
              {seq.primaryAccession}
            </span>
            {statusCfg && (
              <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${statusCfg.cls}`}>
                ✓ {statusCfg.label}
              </span>
            )}
            {seq.identifierScheme && (
              <span className="text-xs bg-slate-100 dark:bg-slate-700 text-slate-500 dark:text-slate-400 px-2 py-0.5 rounded-full font-mono">
                {seq.identifierScheme}
              </span>
            )}
          </div>

          {/* Description */}
          {seq.description && (
            <p className="text-sm text-slate-700 dark:text-slate-200 leading-snug font-medium">
              {seq.description.length > 130
                ? seq.description.slice(0, 127) + "…"
                : seq.description}
            </p>
          )}

          {/* Metadata grid */}
          <div className="grid grid-cols-2 gap-x-4 gap-y-2">
            {seq.organism && (
              <SeqField
                label="Organism"
                value={seq.organism.length > 38 ? seq.organism.slice(0, 35) + "…" : seq.organism}
              />
            )}
            {seq.resourceCategory && <SeqField label="Category" value={seq.resourceCategory} />}
            {seq.assemblyName && <SeqField label="Assembly" value={seq.assemblyName} />}
            {seq.assemblyLevel && <SeqField label="Level" value={seq.assemblyLevel} />}
            {seq.moleculeType && (
              <SeqField label="Molecule" value={seq.moleculeType.toUpperCase()} />
            )}
            {seq.topology && (
              <SeqField
                label="Topology"
                value={seq.topology.charAt(0).toUpperCase() + seq.topology.slice(1)}
              />
            )}
            {seq.sequenceLength !== undefined && seq.sequenceLengthUnit && (
              <SeqField
                label="Genome Size"
                value={`${seq.sequenceLength.toLocaleString()} ${seq.sequenceLengthUnit}`}
              />
            )}
            {seq.taxId && <SeqField label="TaxID" value={String(seq.taxId)} />}
            {seq.lastUpdateDate && <SeqField label="Updated" value={seq.lastUpdateDate} />}
            {seq.genbankAccession && seq.genbankAccession !== seq.primaryAccession && (
              <SeqField label="GenBank" value={seq.genbankAccession} />
            )}
            {seq.refseqAccession && seq.refseqAccession !== seq.primaryAccession && (
              <SeqField label="RefSeq" value={seq.refseqAccession} />
            )}
          </div>

          {/* Downloads */}
          {seq.downloads.length > 0 && (
            <div className="space-y-1.5">
              <p className="text-xs text-slate-400 dark:text-slate-500 font-medium">Downloads</p>
              <div className="flex flex-wrap gap-2">
                {seq.downloads.map((dl) => (
                  <a
                    key={dl.format}
                    href={dl.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-xs bg-teal-50 dark:bg-teal-900/30 text-teal-600 dark:text-teal-400 px-2 py-0.5 rounded-full hover:underline font-medium"
                  >
                    {dl.name} ↓{dl.verified ? "" : " *"}
                  </a>
                ))}
              </div>
              {seq.downloads.some((d) => !d.verified) && (
                <p className="text-xs text-slate-400 dark:text-slate-500 mt-0.5">
                  * URL from NCBI EFetch pattern; not HEAD-verified for this record.
                </p>
              )}
            </div>
          )}

          {/* Available Resources */}
          {seq.availableResources.length > 0 && (
            <div className="space-y-1.5">
              <p className="text-xs text-slate-400 dark:text-slate-500 font-medium">
                Available Resources
              </p>
              <div className="flex flex-wrap gap-1.5">
                {seq.availableResources.map((r) => (
                  <span
                    key={r.type}
                    title={`Provider: ${r.provider}`}
                    className={`text-xs px-2 py-0.5 rounded-full ${
                      r.available
                        ? "bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300"
                        : "bg-slate-50 dark:bg-slate-800/50 text-slate-400 dark:text-slate-500"
                    }`}
                  >
                    {r.type}
                    {r.estimatedCount !== undefined
                      ? ` ~${r.estimatedCount.toLocaleString()}`
                      : ""}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {/* Footer */}
      <div className="px-5 py-3 border-t border-slate-100 dark:border-slate-700/50 space-y-0.5">
        {seq?.resolutionRule && (
          <p className="text-xs text-slate-400 dark:text-slate-500">
            Rule {seq.resolutionRule.slice(-1)} — {RULE_LABEL[seq.resolutionRule] ?? ""}
          </p>
        )}
        <p className="text-xs text-slate-400 dark:text-slate-500 italic">
          Live data — NCBI Entrez (Gene · Assembly · NucCore) · Phase 5.1
        </p>
      </div>
    </div>
  );
}

// ─── Biological Query Resolution card (Phase 5.1.5) ──────────────────────────

/** Tier badge colors */
const TIER_CONFIG = {
  high: {
    badge: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300",
    label: "HIGH",
  },
  medium: {
    badge: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300",
    label: "MEDIUM",
  },
  low: {
    badge: "bg-slate-100 text-slate-500 dark:bg-slate-700 dark:text-slate-400",
    label: "LOW",
  },
} as const;

/** Type chip color — amber family for all types, slight variation on special cases */
function TypeChip({ type }: { type: string }) {
  return (
    <span className="text-xs font-semibold bg-amber-50 dark:bg-amber-900/30 text-amber-700 dark:text-amber-300 px-2 py-0.5 rounded-full border border-amber-200 dark:border-amber-700">
      {type}
    </span>
  );
}

function QueryResolutionCard({
  resolution,
  originalQuery,
}: {
  resolution: NormalizedQuery | null;
  originalQuery: string;
}) {
  const router = useRouter();

  // Don't render if no resolution data at all
  if (!resolution) return null;

  const { gene, organism, disease, protein } = resolution;
  const isUnknown = !gene && !organism && !disease && !protein;
  const tier = toConfidenceTier(resolution.confidence);
  const tierCfg = TIER_CONFIG[tier];
  const isHigh = tier === "high";
  const isMedium = tier === "medium";

  // The primary display label — same precedence used by the orchestrator to
  // derive effectiveQuery (gene > disease > organism > raw query).
  const normalizedLabel = gene?.symbol ?? disease?.name ?? organism?.name ?? resolution.rawQuery;
  const queryChanged = normalizedLabel !== resolution.rawQuery;
  const candidates = resolution.candidates ?? [];
  const entityTypes = [
    gene && "Gene",
    organism && "Organism",
    disease && "Disease",
    protein && "Accession",
  ].filter((v): v is string => Boolean(v));

  function applyResolution() {
    router.push(`/results?q=${encodeURIComponent(normalizedLabel)}`);
  }

  return (
    <div className="rounded-2xl border border-amber-200 dark:border-amber-800/60 bg-white/80 dark:bg-slate-800/60 overflow-hidden shadow-sm backdrop-blur-sm">
      {/* Header */}
      <div className="bg-amber-600 px-5 py-4 flex items-center gap-2 flex-wrap">
        <span className="text-xl">🔍</span>
        <h3 className="font-semibold text-white text-base">Biological Query Resolution</h3>
        <span className={`ml-auto text-xs font-bold px-2.5 py-0.5 rounded-full ${tierCfg.badge}`}>
          {tierCfg.label}
        </span>
        <span className="text-xs font-medium px-2 py-0.5 rounded-full bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-200">
          Phase R
        </span>
      </div>

      <div className="px-5 py-4 space-y-4">

        {/* Unknown / LOW tier — no confident match */}
        {isUnknown && (
          <div className="flex items-start gap-3 rounded-xl bg-slate-50 dark:bg-slate-700/40 px-4 py-3">
            <span className="text-lg mt-0.5">❓</span>
            <div>
              <p className="text-sm font-medium text-slate-700 dark:text-slate-200">
                No confident biological interpretation found
              </p>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                The query &ldquo;{originalQuery}&rdquo; did not match a known accession, gene,
                organism, or disease with sufficient confidence. All modules searched
                using the original query unchanged.
              </p>
            </div>
          </div>
        )}

        {/* Resolved entity info (non-Unknown) */}
        {!isUnknown && (
          <>
            {/* Type + normalized query row */}
            <div className="flex flex-wrap items-center gap-2">
              {entityTypes.map((t) => (
                <TypeChip key={t} type={t} />
              ))}
              {queryChanged && (
                <>
                  <span className="text-xs text-slate-400 dark:text-slate-500">→</span>
                  <span className="text-sm font-semibold text-slate-800 dark:text-slate-100">
                    {normalizedLabel}
                  </span>
                  <span className="text-xs text-slate-400 dark:text-slate-500">
                    (from &ldquo;{resolution.rawQuery}&rdquo;)
                  </span>
                </>
              )}
              {!queryChanged && (
                <span className="text-sm font-semibold text-slate-800 dark:text-slate-100">
                  {normalizedLabel}
                </span>
              )}
            </div>

            {/* Metadata chips row */}
            <div className="flex flex-wrap gap-1.5">
              {gene?.geneId && (
                <span className="text-xs font-mono bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 px-2 py-0.5 rounded-full">
                  ncbi-gene:{gene.geneId}
                </span>
              )}
              {protein?.accession && (
                <span className="text-xs font-mono bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 px-2 py-0.5 rounded-full">
                  {protein.accession}
                </span>
              )}
              {organism && (
                <span className="text-xs bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 px-2 py-0.5 rounded-full">
                  🧬 {organism.name}
                </span>
              )}
              {organism?.taxId && (
                <span className="text-xs font-mono bg-slate-100 dark:bg-slate-700 text-slate-500 dark:text-slate-400 px-2 py-0.5 rounded-full">
                  TaxID {organism.taxId}
                </span>
              )}
              {resolution.confidence > 0 && (
                <span className="text-xs bg-slate-100 dark:bg-slate-700 text-slate-500 dark:text-slate-400 px-2 py-0.5 rounded-full">
                  {Math.round(resolution.confidence * 100)}% confidence
                </span>
              )}
            </div>

            {/* Ambiguity — candidate matches */}
            {resolution.ambiguous && candidates.length > 1 && (
              <div className="space-y-2">
                <p className="text-[10px] text-amber-600 dark:text-amber-400 uppercase tracking-wide font-semibold">
                  ⚠ Ambiguous — multiple candidates
                </p>
                <div className="divide-y divide-slate-100 dark:divide-slate-700/50 rounded-xl border border-amber-200 dark:border-amber-800/50 overflow-hidden">
                  {candidates.slice(0, 5).map((c, i) => (
                    <div key={c.gene?.geneId ?? c.organism?.name ?? i} className="px-3 py-2 flex items-center gap-2 flex-wrap">
                      {c.gene?.geneId && (
                        <span className="text-xs font-mono text-slate-500 dark:text-slate-400">{c.gene.geneId}</span>
                      )}
                      <span className="text-xs font-medium text-slate-700 dark:text-slate-200">
                        {c.gene?.symbol ?? c.organism?.name ?? "—"}
                      </span>
                      {c.organism && c.gene && (
                        <span className="text-xs italic text-slate-400 dark:text-slate-500">{c.organism.name}</span>
                      )}
                      <span className="ml-auto text-xs text-slate-400 dark:text-slate-500">
                        {Math.round(c.confidence * 100)}%
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Evidence trail */}
            {resolution.evidence.length > 0 && (
              <div className="space-y-1">
                <p className="text-[10px] text-slate-400 dark:text-slate-500 uppercase tracking-wide font-medium">
                  Evidence
                </p>
                <ul className="space-y-0.5">
                  {resolution.evidence.map((e, i) => (
                    <li key={i} className="text-xs text-slate-400 dark:text-slate-500 italic">
                      {e.reason}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* HIGH tier — auto-applied banner */}
            {isHigh && queryChanged && (
              <div className="rounded-xl bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800/50 px-4 py-3 flex items-center gap-3">
                <span className="text-base">✓</span>
                <div>
                  <p className="text-xs font-semibold text-emerald-700 dark:text-emerald-300">
                    Normalized query auto-applied
                  </p>
                  <p className="text-xs text-emerald-600 dark:text-emerald-400">
                    All modules searched &ldquo;{normalizedLabel}&rdquo; (HIGH confidence —
                    no confirmation required).
                  </p>
                </div>
              </div>
            )}

            {/* HIGH tier — normalized query same as original, just confirm type */}
            {isHigh && !queryChanged && (
              <div className="rounded-xl bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800/50 px-4 py-3">
                <p className="text-xs text-emerald-700 dark:text-emerald-300">
                  ✓ Query resolved with HIGH confidence — all modules searched as-is.
                </p>
              </div>
            )}

            {/* MEDIUM tier — suggestion banner with Apply button */}
            {isMedium && (
              <div className="rounded-xl bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800/50 px-4 py-3 flex items-start gap-3">
                <span className="text-base mt-0.5">💡</span>
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-semibold text-amber-700 dark:text-amber-300">
                    Suggested interpretation (MEDIUM confidence)
                  </p>
                  <p className="text-xs text-amber-600 dark:text-amber-400 mt-0.5">
                    Modules searched using your original query. Accept the suggestion
                    below to re-search with the normalized form.
                  </p>
                </div>
                {queryChanged && (
                  <button
                    onClick={applyResolution}
                    className="shrink-0 text-xs font-semibold bg-amber-600 hover:bg-amber-700 text-white px-3 py-1.5 rounded-full transition-colors"
                  >
                    Apply &ldquo;{normalizedLabel}&rdquo;
                  </button>
                )}
              </div>
            )}
          </>
        )}
      </div>

      {/* Footer */}
      <div className="px-5 py-3 border-t border-amber-100 dark:border-amber-900/30">
        <p className="text-xs text-slate-400 dark:text-slate-500 italic">
          Biological Query Resolution · Phase R
        </p>
      </div>
    </div>
  );
}

function SeqField({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-[10px] text-slate-400 dark:text-slate-500 uppercase tracking-wide font-medium">
        {label}
      </p>
      <p className="text-xs text-slate-700 dark:text-slate-300 font-medium truncate">{value}</p>
    </div>
  );
}

// ─── AI result section ────────────────────────────────────────────────────────

function ResultSection({
  icon,
  title,
  color,
  items,
  itemType,
}: {
  icon: string;
  title: string;
  color: "blue" | "purple" | "indigo" | "emerald";
  items: string[];
  itemType: string;
}) {
  const colorMap = {
    blue: {
      header: "bg-blue-600",
      badge: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300",
      bullet: "bg-blue-500",
    },
    purple: {
      header: "bg-purple-600",
      badge: "bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300",
      bullet: "bg-purple-500",
    },
    indigo: {
      header: "bg-indigo-600",
      badge: "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/40 dark:text-indigo-300",
      bullet: "bg-indigo-500",
    },
    emerald: {
      header: "bg-emerald-600",
      badge: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300",
      bullet: "bg-emerald-500",
    },
  };

  const c = colorMap[color];

  return (
    <div className="rounded-2xl border border-slate-200 dark:border-slate-700 bg-white/80 dark:bg-slate-800/60 overflow-hidden shadow-sm backdrop-blur-sm">
      <div className={`${c.header} px-5 py-4 flex items-center gap-2`}>
        <span className="text-xl">{icon}</span>
        <h3 className="font-semibold text-white text-base">{title}</h3>
        <span className={`ml-auto text-xs font-medium px-2 py-0.5 rounded-full ${c.badge}`}>
          {items.length} found
        </span>
      </div>
      <ul className="divide-y divide-slate-100 dark:divide-slate-700/50">
        {items.map((item, i) => (
          <li key={i} className="px-5 py-4 flex gap-3 items-start">
            <span className={`mt-1.5 h-2 w-2 rounded-full shrink-0 ${c.bullet}`} />
            <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{item}</p>
          </li>
        ))}
      </ul>
      <div className="px-5 py-3 border-t border-slate-100 dark:border-slate-700/50">
        <p className="text-xs text-slate-400 dark:text-slate-500 italic">
          Powered by AI — {itemType}s generated for your query
        </p>
      </div>
    </div>
  );
}
